src/main/java/com/samsamhajo/deepground/studyGroup/entity/GroupStatus.java
src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroup.java

- StudyGroup 관련 엔티티를 새로 작성했습니다.
- 그룹 상태(`group_status`)를 Enum 타입(`GroupStatus`)으로 관리하도록 변경했습니다.
- 모든 항목은 데이터 무결성을 위해 `NOT NULL` 제약 조건을 적용했습니다.
---
-  StudyGroup 엔티티 작성
- 기본 키(`study_group_id`) 설정
- 필수 필드 매핑 (`chat_room_id`, `title`, `explanation`, 등)
- `explanation` 필드는 `TEXT` 타입으로 매핑
- 모든 항목에 대해 `nullable = false` 설정
-  GroupStatus Enum 작성
- RECRUITING(모집 중), ONGOING(진행 중), COMPLETED(완료), CANCELLED(취소) 4개 상태 정의
-  group_status를 `@Enumerated(EnumType.STRING)`으로 매핑
-  BaseEntity 상속 처리로 공통 필드 관리
-  isOffline(Boolean), studyLocation(Nullable) 필드 작성
-  관련 이슈 번호: #11
---
- StudyGroup 엔티티를 작성하여 스터디 그룹의 주요 정보(채팅방, 모집 일정, 인원 등)를 저장할 수 있도록 했습니다.
- 특히 `explanation` 필드는 TEXT 타입으로 선언하여 긴 설명을 수용할 수 있도록 했습니다.
- 모든 주요 컬럼은 `NOT NULL` 처리하여 데이터의 안정성을 확보했습니다.
---
- 그룹 상태를 문자열이 아닌 `Enum` 타입으로 관리해 가독성과 타입 …

[Feature] StudyGroup 엔티티 및 GroupStatus Enum 작성 (연관관계 제외)

---

src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupMember.java

- 스터디 그룹 참여자 정보를 저장하는 `StudyGroupMember` 엔티티를 생성하였습니다.
- 현재는 연관관계 없이 `memberId`, `studyGroupId`를 단순 필드(Long)로만 저장하며, 추후 연관관계 매핑은 별도 PR로 진행할 예정입니다.
---
-  `StudyGroupMember` 엔티티 클래스 생성
-  기본 키 `group_id`에 대한 ID 매핑 설정
-  `memberId`, `studyGroupId`를 단순 Long 타입으로 정의 (연관관계 미포함)
-  `isAllowed` 필드 정의 (nullable Boolean)
-  `BaseEntity` 상속으로 공통 필드 관리
-  관련 이슈 번호: #12
---
- `group_id`: 참여 식별자 (PK)
- `member_id`: 참여 멤버 ID
- `study_group_id`: 참여 그룹 ID
- `is_allowed`: 참여 승인 여부 (nullable)
---
- 현재 `Member`, `StudyGroup` 엔티티의 개발 브랜치와 충돌을 방지하기 위해  
연관관계는 제거하고 ID만 저장하도록 구성하였습니다.
- 이후 `@ManyToOne` 등 연관관계 매핑은 안정화된 이후 별도 PR로 다룰 예정입니다.
---
- 연관관계 매핑 (`StudyGroup` 및 `Member`와 `@ManyToOne`) 적용 PR 예정
- `StudyGroup` → `StudyGroupMember` 방향의 양방향 매핑 도입 고려
---
-  Entity 스캔 및 Context 로딩 정상 확인
-  새로운 의존성 없음 …

[Feature] StudyGroupMember 엔티티 구현 (연관관계 제외)

---

src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupComment.java

스터디 그룹 내 댓글을 저장하는 `StudyGroupComment` 엔티티를 생성하였습니다.  
현재는 연관관계 없이 `memberId`, `studyGroupId`를 Long 필드로만 저장합니다.
---
-  `StudyGroupComment` 엔티티 클래스 생성
-  `comment_id`를 기본 키로 설정
-  `studyGroupId`, `memberId`를 단일 Long 필드로 명시 (연관관계 제외)
-  `content` 필드를 `TEXT` 타입으로 선언
-  `BaseEntity` 상속
-  관련 이슈 번호: #13
---
- `comment_id`: 댓글 고유 ID
- `study_group_id`: 댓글이 달린 스터디 그룹 ID
- `member_id`: 댓글 작성자 ID
- `content`: 댓글 본문 (nullable 불가, TEXT)
---
- `StudyGroup` 및 `Member`와의 연관관계 매핑 추가 예정 (`@ManyToOne`)
- 댓글에 대한 대댓글 기능 추가 시, `StudyGroupReply`와 연계 예정
---
-  Entity 스캔 및 Context 로딩 정상 확인
-  새로운 의존성 없음 (`build.gradle` 영향 없음)
-  코드 스타일 및 컨벤션 준수 확인
---
- 연관관계가 제거되어 있어 테스트/기능 개발이 충돌 없이 진행 가능
- 추후 기능 연계 시 `@ManyToOne`으로 유연하게 확장 가능하도록 설계
---
- `content` 필드에 대한 타입 및 null 허용 여부 검토해주세요.
- 네이밍, 포맷, 주석 등 팀 컨벤션과의 일관성 …

[Feature] StudyGroupComment 엔티티 구현 (연관관계 제외)

---

src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupReply.java

스터디 그룹 댓글에 대한 **대댓글을 저장**하는 `StudyGroupReply` 엔티티를 생성하였습니다.  
연관관계 없이 외래 키는 ID(Long)로만 저장하도록 구성하였습니다.
---
-  `StudyGroupReply` 엔티티 클래스 생성
-  기본 키 `study_group_reply_id` 매핑
-  댓글(comment), 멤버(member)는 단일 Long 타입으로 저장
-  `content`는 NOT NULL 필드로 선언
-  `BaseEntity` 상속 적용
-  관련 이슈 번호: #14 
---
- `study_group_reply_id`: 대댓글 고유 ID
- `comment_id`: 연결된 댓글 ID
- `member_id`: 작성자 ID
- `content`: 대댓글 내용
---
- 추후 `StudyGroupComment`와의 연관관계(`@ManyToOne`) 매핑 예정
---
-  Entity 스캔 및 ApplicationContext 로딩 정상 확인
-  코드 컨벤션 및 스타일 점검 완료
-  신규 의존성 없음 (`build.gradle` 영향 없음)
---
- 연관관계 없이 ID만 사용하는 구조로 설계되어 현재 구조에서의 충돌을 피할 수 있음
---
- `StudyGroupReply` 필드와 DB 스키마가 일치하는지 확인해주세요.
- `content`의 NOT NULL 여부가 팀의 정책과 맞는지 확인해주세요.
- 구조적 확장성(연관관계 도입 시 유연성) 여부 확인해주세요.
- 코드 네이밍, 어노테이션, 포맷이 일관성을 유지하고 있는지 검토해주세요.
Closes #14

[Feature] StudyGroupReply 엔티티 구현 (연관관계 제외)

---

src/main/java/com/samsamhajo/deepground/calendar/entity/MemberStudySchedule.java

* 스터디 참여자의 개인 일정 상태를 기록하기 위한 MemberStudySchedule 엔티티를 생성했습니다.  
* 각 스터디 일정에 대해 개별 구성원이 작성하는 메모, 참석 가능 여부, 중요 표시 등의 정보를 저장합니다.
* 다음과 같은 필드로 구성되어 있습니다:
- `memo`: 자유로운 텍스트 메모 입력 필드 (nullable)
- `isAvailable`: 해당 스케줄에 참여 가능한지 여부 (필수값)
- `isImportant`: 중요 여부 표시 (nullable)
- close #24
* StudySchedule, Member 엔티티와의 다대일 연관관계 설정 예정 (`@ManyToOne`)
* 스터디 캘린더 기능에서 해당 엔티티를 통해 개인별 메모/참석 여부 정보를 표시할 예정
---

[Feature] 멤버 스터디 스케줄 엔티티 구현

---

src/main/java/com/samsamhajo/deepground/chat/entity/ChatRoomMember.java

* 채팅방에 참여한 멤버 정보를 저장하는 `ChatRoomMember` 엔티티를 생성하였습니다.
- `ChatRoomMember` 엔티티 클래스 생성
- 관련 이슈 번호 #37 
- `chat_room_member_id`:  채팅방 멤버 고유 ID
- `member_id`: 채팅방에 참여한 멤버 ID
- `chat_room_id`: 참여한 채팅방 ID
- `ChatRoomMember` 테이블 생성 확인
- 새로운 의존성 없음
- 연관관계가 필요한 필드는 주석 처리했습니다.
---
Closes #37

[Feature] ChatRoomMember 엔티티 구현

---

src/main/java/com/samsamhajo/deepground/global/BaseDocument.java
src/main/java/com/samsamhajo/deepground/notification/entity/Notification.java
src/main/java/com/samsamhajo/deepground/notification/entity/NotificationMessage.java
src/main/java/com/samsamhajo/deepground/notification/entity/NotificationType.java
src/main/java/com/samsamhajo/deepground/notification/entity/data/ChatMessageNotificationData.java
src/main/java/com/samsamhajo/deepground/notification/entity/data/FriendRequestNotificationData.java
src/main/java/com/samsamhajo/deepground/notification/entity/data/NotificationData.java
src/main/java/com/samsamhajo/deepground/notification/entity/data/StudyGroupNotificationData.java
src/main/java/com/samsamhajo/deepground/notification/entity/data/StudyScheduleNotificationData.java
src/main/resources/application.yml

* 알림을 저장할 수 있는 `Notification` 엔티티와 관련 클래스를 생성했습니다.
- MongoDB 자동 인덱스 생성 활성화
- `Notification`에서 `@CompoundIndex`를 사용하기 위해 추가했습니다.
- `Notification` 엔티티 클래스 생성
- `NotificationMessage` 엔티티 클래스 생성
- `NotificationType` enum 클래스 생성
- FRIEND_REQUEST(친구 요청)
- STUDY_GROUP_INVITE(스터디 그룹 초대)
- STUDY_GROUP_JOINED(스터디 그룹 가입)
- SCHEDULE_CREATED(스터디 일정 생성)
- SCHEDULE_REMINDER(스터디 일정 알림)
- CHAT_MESSAGE(새 메시지)
- `NotificationData` 추상 클래스 및 구현체 생성
- FriendRequestNotificationData(친구 요청을 받았을 때)
- StudyGroupNotificationData(스터디 그룹 가입 수락 / 초대받았을 때)
- StudyScheduleNotificationData(일정이 생성되었을 때 / 일정 알림이 필요할 때)
- ChatMessageNotificationData(새 메시지를 받았을 때)
- `BaseDocument`에서 사용하지 않는 공통 필드 제거
- 지금은 Document를 저장할 때 softDelete가 필요하지 않다고 생각해 제거했습니다.
- 나중에 알림이나 채팅을 삭제하는 기능이 필요할 때 deleted를 추가하는 것이 좋을 것 같습니다.
- 관련 이슈 번호 #35 …

[Feature] 알림 엔티티 구현

---

src/main/java/com/samsamhajo/deepground/chat/entity/ChatMessage.java
src/main/java/com/samsamhajo/deepground/chat/entity/ChatMessageMedia.java

* 채팅 메시지를 저장할 수 있는 `ChatMessage` 엔티티를 생성했습니다.
- `ChatMessage` 엔티티 클래스 생성
- `ChatMessageMedia` 클래스 생성
- 관련 이슈 번호 #40
* chat_message_id: 채팅 메시지 고유 Id
* chat_room_id: 채팅방 Id
* sender_id: 메시지를 보낸 멤버 Id
* message: 메시지 내용
* media: 미디어 리스트(ChatMessageMedia)
* chat_room_id를 오름차순으로, created_at을 내림차순으로 정렬하는 복합 인덱스 사용
* media_url: 미디어 URL
* file_name: 파일 이름
* file_size: 파일 크기
* extension: 확장자
- 기능 정상 동작 확인
---
Closes #40

[Feature] 채팅 메시지 엔티티 구현

---

src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroup.java
src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupComment.java
src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupMember.java
src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupReply.java

- 기존 엔티티에서 `memberId`, `studyGroupId` 등의 단순 필드 기반 외래키를 사용하고 있었으나,  
객체지향적으로 설계하기 위해 이를 실제 연관관계(@ManyToOne 등)로 매핑하였습니다.
- 생성자 대신 `정적 팩토리 메서드 (of)`를 통해 객체 생성을 명시적으로 하도록 구조를 개선하였습니다.
---
-  `StudyGroupMember`, `StudyGroupComment`, `StudyGroupReply`의 `memberId` → `Member` 객체로 변경
-  `StudyGroupComment`, `StudyGroupReply`의 `studyGroupId`, `commentId` → 연관 엔티티로 변경
-  모든 엔티티에 private 생성자 및 정적 팩토리 메서드(`of`) 추가
-  `@JoinColumn`을 이용한 연관관계 설정
- 도메인 생성 책임을 `StudyGroup.of(...)`로 분리
- `members`, `comments` 양방향 관계 매핑 (mappedBy)
- `Long memberId` → `Member member`로 변경
- `of(Member, StudyGroup, Boolean)` 도입
- `studyGroup`, `member` 모두 객체 참조로 변경
- `of(StudyGroup, Member, String)` 형태로 생성
- `comment`, `member` 모두 객체 참조로 변경
- `of(StudyGroupComment, Member, String)` 제공
---
- 댓글, 대댓글 조회 시 연관관계 자동 fetch 전략 튜닝 필요 …

[Refactor] StudyGroup 관련 엔티티 정적 팩토리 및 연관관계 매핑 리팩토링

---

src/main/java/com/samsamhajo/deepground/calendar/entity/MemberStudySchedule.java
src/main/java/com/samsamhajo/deepground/calendar/entity/StudySchedule.java

* Calendar 도메인 내 StudySchedule, MemberStudySchedule 엔티티 간의 연관관계를 매핑했습니다.
*  다른 도메인(StudyGroup, Member)과의 연관관계도 함께 설정했습니다.
* 생성자를 private으로 변경하고, 정적 팩토리 메서드를 추가하여 객체 생성의 일관성을 유지했습니다.
* 연관관계를 활용한 서비스 및 API 구현 예정
의견 있으시면 편하게 남겨주세요
---
Closes #45

[Refactor] 캘린더 관련 정적 팩토리 메서드 추가 및 연관관계 매핑

---

src/main/java/com/samsamhajo/deepground/interest/entity/Interest.java
src/main/java/com/samsamhajo/deepground/interest/entity/MemberInterest.java
src/main/java/com/samsamhajo/deepground/member/entity/Member.java
src/main/java/com/samsamhajo/deepground/techStack/entity/MemberTechStack.java
src/main/java/com/samsamhajo/deepground/techStack/entity/TechStack.java

- 멤버, 관심사, 기술스택 관련 생성자 및 연관관계 매핑을 추가했습니다.
- `Member`에서 `mappedBy`를 활용하여 양방향 연관관계를 매핑 (`MemberInterest`, `MemberTechStack`)
- `Member`, `Interest`, `TechStack` 엔티티에 생성자 추가
- 관련 이슈 번호 (`#57`)

[Refactor] 멤버, 관심사, 기술스택 관련 엔티티 생성자 및 연관관계 매핑

---

build.gradle
src/main/java/com/samsamhajo/deepground/global/config/RedisConfig.java
src/main/java/com/samsamhajo/deepground/global/config/WebSocketConfig.java
src/main/java/com/samsamhajo/deepground/global/config/WebSocketSecurityConfig.java
src/main/java/com/samsamhajo/deepground/global/message/MessagePublisher.java
src/main/java/com/samsamhajo/deepground/global/message/SimpMessagePublisher.java
src/main/resources/application.yml

* WebSocket과 Redis를 사용하기 위한 설정을 추가했습니다.
- WebSocket 관련 의존성 추가 (`spring-boot-starter-websocket`, `spring-security-messaging`)
- WebSocket, WebSocketSecurity 설정 추가
- Redis 설정 추가
- `application.yml`에 Redis 연결 설정 추가
- `MessagePublisher` 추상 클래스 및 구현체 생성
- Redis Pub/Sub 등 메시지 브로커가 필요할 때 유연하게 변경할 수 있도록 설계했습니다.
- 기능 정상 동작 확인
- 새로운 의존성 추가 여부 확인 (`build.gradle`에 `spring-boot-starter-websocket`, `spring-security-messaging` 추가)
- Redis 설치가 필요합니다.
- Redis 연결을 위한 환경 변수들을 .env에 추가해야 합니다.
```env
REDIS_HOST=
REDIS_PORT=
REDIS_PASSWORD=
```
---
Closes #61

[Feature] WebSocket & Redis 기본 설정

---

src/main/java/com/samsamhajo/deepground/chat/repository/ChatRoomRepository.java
src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCreateRequest.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCreateResponse.java
src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupMember.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupMemberRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
src/main/java/com/samsamhajo/deepground/studyGroup/success/StudyGroupSuccessCode.java
src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupServiceIntegrationTest.java
src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupServiceTest.java

스터디 그룹을 생성할 수 있는 API를 구현하였습니다. 사용자가 제목, 설명, 일정, 정원 등의 정보를 입력하면 DB에 저장되며, 생성자는 자동으로 해당 스터디의 참여자로 등록됩니다.
-  `StudyGroupCreateRequest`, `StudyGroupCreateResponse` DTO 설계
-  스터디 생성 API 구현 (`StudyGroupController`, `StudyGroupService`)
-  유효성 검증 로직 작성
-  `StudyGroup`, `StudyGroupMember` 연관 관계 설정 및 저장 로직 작성
-  단위 및 통합 테스트 작성 (`@Mock`, `@Transactional` 기반)
- 사용자가 요청을 보내면 ChatRoom이 생성되고, StudyGroup과 StudyGroupMember가 함께 생성됩니다.
- `StudyGroupCreateRequest`로 요청을 받고, 성공 시 `StudyGroupCreateResponse`를 반환합니다.
```http
POST /study-group
Authorization: Bearer <token>
Content-Type: application/json
{
"title": "모각코 스터디",
"explanation": "매일 오전 9시 모여서 코딩하는 스터디입니다.",
"studyStartDate": "2025-05-19",
"studyEndDate": "2025-06-11",
"recruitStartDate": "2025-05-12",
"recruitEndDate": "2025-05-17",
"groupMemberCount": …
```

[Feature] 스터디 그룹 생성 기능 구현

---

src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupDetailResponse.java
src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroup.java
src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupMember.java
src/main/java/com/samsamhajo/deepground/studyGroup/exception/StudyGroupNotFoundException.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
src/main/java/com/samsamhajo/deepground/studyGroup/success/StudyGroupSuccessCode.java
src/test/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepositoryTest.java
src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupServiceDetailsTest.java

스터디 그룹 상세 정보를 조회할 수 있는 API를 구현했습니다. 작성자, 참여자 목록, 댓글 목록을 함께 조회하도록 쿼리를 최적화하고 DTO에 반영했습니다.
-  스터디 그룹 상세 조회용 Repository 쿼리 작성 (`findWithMemberAndCommentsById`)
-  서비스 로직 구현 (`getStudyGroupDetail`)
-  DTO(`StudyGroupDetailResponse`)에 참여자 목록 및 댓글 목록 필드 추가
-  Controller에 상세 조회 API 추가 (`GET /study-group/{studyGroupId}`)
-  통합 테스트 및 서비스 테스트 작성
- `@Query`를 통해 작성자, 멤버, 댓글을 한 번에 Fetch Join
- 존재하지 않는 경우 `StudyGroupNotFoundException` 반환
- 기존 필드 외에 참여자 목록 (`List<String> participants`) 추가
- 댓글 목록 (`List<String> comments`) 추가
- 통합 테스트(`IntegrationTestSupport` 상속) 기반으로 Service 단 검증
- Mock 데이터: 작성자 + 참여자 + 댓글 생성 후 검증
- 댓글의 구조 고도화 (작성자, 시간 포함 등)
- 참여자 수 기준으로 모집 상태 판단 기능 추가 예정
- `@EntityGraph` 도입 검토로 Fetch Join 복잡도 개선
-  기능 정상 동작 확인 (`스터디 제목`, `참여자 수`, `댓글 수` 검증)
-  새로운 의존성 추가 없음
-  코드 스타일 및 컨벤션 준수
-  기존 테스트 …

[Feature] 스터디 상세 조회 API 구현

---

src/main/java/com/samsamhajo/deepground/friend/Dto/FriendDto.java
src/main/java/com/samsamhajo/deepground/friend/Dto/ResponseDto.java
src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
src/main/java/com/samsamhajo/deepground/friend/repository/FriendRepository.java
src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
src/test/java/com/samsamhajo/deepground/Friend/FriendController/FriendRequestTest.java

친구 요청 목록을 조회하는 API를 구현하였습니다. 해당 기능을 통해 사용자가 자신이 보낸 친구 요청 목록을 확인할 수 있습니다
- `FriendRepository`에 JPQL 쿼리 메서드 추가
- 친구 요청 목록 API 구현
- 테스트 코드 작성
- 사용자가 보낸 친구 요청만 필터링해 조회합니다.
- 받은 요청 목록 기능 별도 구현 예정
- 요청 수락/거절 API 추가 예정
- 기능 정상 동작 확인
- 기존 테스트 통과
-
-FriendService 단위 테스트에서는 예외 처리 케이스 필요 없음
---
closes #91

[Feature] 친구 요청 목록 기능 구현

---

build.gradle
src/main/java/com/samsamhajo/deepground/DeepgroundApplication.java
src/main/java/com/samsamhajo/deepground/friend/Exception/FriendErrorCode.java
src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
src/main/java/com/samsamhajo/deepground/friend/entity/Friend.java
src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
src/main/resources/application.yml
src/test/java/com/samsamhajo/deepground/Friend/FriendController/FriendRequestTest.java
src/test/java/com/samsamhajo/deepground/Friend/FriendRequestTest.java

친구 요청을 취소하는 API를 구현하였습니다. 해당 기능을통해 사용자가 자신이 보낸 친구 요청에 대해서 취소할 수 있습니다.
- 친구 요청 취소 API 구현 (`cancelFriendRequest`)
- 서비스 로직 구현 (`cancelFriendRequest`)
- 친구 요청 취소 에러 코드 작성(`REQUEST_NOT_FOUND`)
- 친구 요청 목록 조회 시 실시간으로 반영되는지 검증
- 친구 요청 취소 시 알림 연동 검토
- 기능 정상 동작 확인
- 기존  테스트 전부 통과 
- 추가 예외 사항에 대해서 확인 
---
Closes #92

[Feature] 친구 요청 취소 기능 구현

---

src/main/java/com/samsamhajo/deepground/calendar/controller/StudyScheduleController.java
src/main/java/com/samsamhajo/deepground/calendar/exception/ScheduleErrorCode.java
src/main/java/com/samsamhajo/deepground/calendar/exception/ScheduleException.java
src/main/java/com/samsamhajo/deepground/calendar/exception/ScheduleSuccessCode.java
src/main/java/com/samsamhajo/deepground/calendar/service/StudyScheduleService.java
src/test/java/com/samsamhajo/deepground/calendar/controller/StudyScheduleControllerTest.java
src/test/java/com/samsamhajo/deepground/calendar/service/StudyScheduleServiceTest.java

* StudyScheduleController와 StudyScheduleService의 응답 표준화를 위한 리팩토링 작업을 진행하였습니다.
* 일정 조회 및 삭제 API 작성
closes #173

[Refactor] 스케줄 도메인 관련 응답 표준화 리팩토링

---

src/main/java/com/samsamhajo/deepground/friend/Dto/FriendDto.java
src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
src/main/java/com/samsamhajo/deepground/friend/repository/FriendRepository.java
src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendReceiveTest.java

받은 친구 요청 목록에 대해서 조회하는 기능을 구현하였니다
- `FriendRepository`에 JPQL쿼리 메서드 추가(`findReceiveRequests`)
- 받은 친구 요청 목록 API 구현(`getReceiveFriendRequests`)
- `FriendDto` 정적 팩토리 메서드(`fromReceived`) 추가
- 받은 친구 요청 목록 서비스 로직 구현 (`findFriendReceive`)
- 테스트 코드 작성
- 받은 친구 요청에 대한 목록을 조회합니다.
- 쿼리 작성(`findReceiveRequests`)
receiverId가 일치하고, 상태가 "REQUEST"인 친구 요청만 조회합니다
- 요청 수락/거절 API 추가 예정
- 요청이 수락/거절, 요청 취소에 대한 친구 받은 요청 목록에서 제외 테스트 확인 예정
- 기능 정상 동작 확인
- 코드 스타일 및 컨벤션 준수
- 기존 테스트 통과
closes #94

[Feature] 받은 친구 요청 목록 조회 기능 구현

---

src/main/java/com/samsamhajo/deepground/friend/Exception/FriendErrorCode.java
src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendRequestTest.java

- 다른 사용자의 프로필에서 친구 요청을 보낼 수 있는 기능을 구현했습니다
- 
- 프로필에서 친구 요청 보내기API 작성(`requestProfileFriend`)
- 프로필에서 친구 요청 보내기 서비스 로직 작성(`sendProfileFriendRequest`) 
- 예외 사항 추가(`INVALID_MEMBER_ID`,`REQUEST_ALREADY_RECEIVED`)
- 테스트 코드 작성
- 프로필의 친구 요청에서 친구 요청을 보낼 수 있습니다
- 요청시 `Friend` 엔티티 상태는 `REQUEST`로 변경됩니다.
- 추후에 `requestProfileFriend` url (/members/from-profile/{recevierId} 로 변경 예정
- 추후에 `INVALID_MEMBER_ID` 예외 사항 (MemberErrorCode로 변경 예정
- 친구 목록 기능 구현 예정
- 친구 삭제 기능 구현 에정
- 기능 정상 동작 확인
- 기존 테스트 통과 
- 프로필 친구 요청 정상 작동
- 존재하지 않는 요청자 Id에 대해 예외 발생
- 자신의 계정에 대한 친구 요청 예외 발생
- 이미 친구 상태에 대한 친구 요청 예외 발생
- 중복 친구 요청에 대해 예외 발생
- 받은 친구 요청에 대해 예외 발생
Closes #100

[Feature] 프로필에서 친구 요청 기능 구현

---

src/main/java/com/samsamhajo/deepground/friend/Exception/FriendErrorCode.java
src/main/java/com/samsamhajo/deepground/friend/Exception/FriendSuccessCode.java
src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
src/main/java/com/samsamhajo/deepground/friend/repository/FriendRepository.java
src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
src/main/java/com/samsamhajo/deepground/member/exception/MemberErrorCode.java
src/main/java/com/samsamhajo/deepground/member/exception/MemberException.java
src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendReceiveTest.java

친구 요청 수락 기능을 구현했습니다
- 친구 요청 수락 API 구현 (`acceptFriendRequest`)
- 친구 요청 수락 서비스 로직 구현 
- 친구 요청 수락 관련 예외 로직 추가
- 친구 요청의 ID, 수신자, 상태 값을 기준으로 특정 상태의 친구 관계 여부를 확인할 수 있는 쿼리 메서드(existsByIdAndReceiveMemberAndStatus) 작성
- 테스트 코드 작성
- 친구 요청에 대해서 수락 처리를 수 있습니다
- 수락 시, `Friend` 엔티티의 상태를 `"ACCEPT"`로 변경합니다.
-  쿼리 작성(acceptFriendRequest) 및 쿼리 메서드 사용
-  친구 수락 후:
- 친구 목록에서 정상 조회 여부 확인
- 보낸 친구 요청 목록 및 받은 친구 요청 목록에서 제외되는 확인 
- 기능 정상 동작 확인
- 코드 스타일 및 컨벤션 준수
- 기존 테스트 통과 
- 추가한 필요한 예외 사항이 있는지 확인해주시면 감사하겠습니다
---
closes #96

[Feature] 친구 요청 수락 기능 구현

---

src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupMemberRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupJoinService.java
src/main/java/com/samsamhajo/deepground/studyGroup/success/StudyGroupSuccessCode.java
src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupJoinServiceTest.java

- 사용자가 특정 스터디 그룹에 참가 요청을 보낼 수 있는 기능을 구현했습니다.
- 요청은 `StudyGroupMember` 엔티티에 `isAllowed = false` 상태로 저장되며, 요청 중복 및 이미 참여 중인 경우에 대한 예외 처리를 포함합니다.
---
-  참가 요청 기능 서비스 로직(`StudyGroupJoinService`) 구현
-  요청 중복 방지 및 상태 값 (`isAllowed = false`) 기반 대기 상태 저장 처리
-  `StudyGroupJoinServiceTest` 통합 테스트 작성
-  참가 요청 API (`POST /study-group/{id}/join`) 구현
-  `StudyGroupJoinController` 생성
-  성공 응답 코드 `REQUEST_JOIN_SUCCESS` 추가
-  `StudyGroupMemberRepository`에 조회 메서드 추가 (`existsByMemberAndStudyGroup`, `findByMemberAndStudyGroup`)
---
- 요청자는 인증된 `Member`로 가정하고 `@RequestAttribute("member")`를 통해 주입
- 중복 요청 또는 기존 참여 여부 확인 후 예외 발생 (`IllegalStateException`)
- 요청은 `StudyGroupMember.of(member, studyGroup, false)`로 생성하여 `isAllowed = false` 상태로 저장
- 추후 관리자가 수락할 경우 `allowMember()` 호출로 상태 변경 가능
---
- 관리자 승인/거절 API 및 상태 변경 …

[Feature] 스터디 그룹 참가 요청 기능 구현

---

src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupCommentController.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCommentRequest.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCommentResponse.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupCommentRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupCommentService.java
src/main/java/com/samsamhajo/deepground/studyGroup/success/StudyGroupSuccessCode.java
src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupCommentServiceTest.java

- 스터디 그룹 상세 페이지에서 인증된 사용자가 댓글을 작성할 수 있는 기능을 구현했습니다.
- 댓글 저장과 동시에 응답 DTO로 작성자의 닉네임, 작성 내용, 작성 시간이 반환됩니다.
---
-  `StudyGroupComment` 엔티티 정의 및 관계 매핑
-  댓글 작성 요청/응답 DTO (`StudyGroupCommentRequest`, `StudyGroupCommentResponse`) 구현
-  댓글 작성 서비스 (`StudyGroupCommentService.writeComment`) 구현
-  댓글 작성 API 컨트롤러 (`StudyGroupCommentController.writeComment`) 구현
-  통합 테스트 (`StudyGroupCommentServiceTest`) 작성 및 통과
-  성공 응답 코드 `StudyGroupSuccessCode.COMMENT_CREATE_SUCCESS` 정의
- `@NotNull`, `@NotBlank`를 활용한 유효성 검증 포함
- `StudyGroupCommentResponse`는 응답 시 사용자 닉네임, 내용, 생성 시각을 포함
---
- 인증된 사용자에 한하여 댓글 작성 가능 (`@RequestAttribute("member")`)
- POST `/study-group/comments`로 요청
- 작성 완료 시 `201 CREATED` 상태와 함께 댓글 정보 응답
---
- 댓글 목록 조회 및 삭제/수정 기능 추가 예정
- 스터디 상세 조회 응답에 댓글 목록 포함 예정 (`StudyGroupDetailResponse` 확장)
---
-  기능 …

[Feature] 스터디 그룹 댓글 작성 기능 구현

---

src/main/java/com/samsamhajo/deepground/calendar/controller/MemberStudyScheduleController.java
src/main/java/com/samsamhajo/deepground/calendar/dto/MemberStudyScheduleRequestDto.java
src/main/java/com/samsamhajo/deepground/calendar/dto/MemberStudyScheduleResponseDto.java
src/main/java/com/samsamhajo/deepground/calendar/dto/StudyScheduleResponseDto.java
src/main/java/com/samsamhajo/deepground/calendar/repository/MemberStudyScheduleRepository.java
src/main/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleService.java
src/main/java/com/samsamhajo/deepground/calendar/service/StudyScheduleService.java
src/test/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleServiceTest.java
src/test/java/com/samsamhajo/deepground/calendar/service/StudyScheduleServiceTest.java

* StudySchedule 삭제 로직 리팩토링 및 관련된 MemberStudySchedule 연동 삭제 처리
* 서비스단 DTO 빌더 패턴을 정적 팩토리 메서드 방식으로 개선
- StudySchedule 존재하지 않을 때 SCHEDULE_NOT_FOUND 사용하도록 수정
- StudySchedule 삭제 시 연관된 MemberStudySchedule도 함께 삭제되도록 서비스 로직 및 테스트 코드 수정
- 반복적인 DTO 빌더 호출을 정적 팩토리 메서드(from)로 리팩토링
- MemberStudySchedule 관련 파일 추가
* MemberStudySchedule 관련 기능 확장 예정
- 기능 정상 동작 확인
- 스터디 일정 삭제 시 관련 MemberStudySchedule 함께 삭제되는지 검증
- StudySchedule이 존재하지 않을 때 SCHEDULE_NOT_FOUND 예외 발생 확인
-  빌더 방식 → 정적 팩토리 메서드 전환 후 응답 DTO 값 정상 매핑 여부 확인
- MemberStudySchedule은 양방향 매핑 없이 수동 삭제 방식으로 처리했습니다.
---
closes #196

[Refactor] 캘린더 도메인 리팩토링 및 MemberStudySchedule 파일 추가

---

src/main/java/com/samsamhajo/deepground/friend/Exception/FriendSuccessCode.java
src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
src/main/java/com/samsamhajo/deepground/friend/repository/FriendRepository.java
src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendsTest.java

친구 목록에 대해서 조회하는 기능을 구현하였습니다
- 친구 목록 API 구현( `getFriendList` )
- 친구 목록 서비스 로직 구현 (`getFriendByMemberId`)
- `FriendRepository`에 JPQL쿼리 메서드 추가 (`findAllByMemberIdAndFriendStatus`)
- 성공 읍답 메세지 추가(`FRIEND_SUCCESS_GET_LIST`)
- 테스트 코드 작성
- 회원이 보낸 친구 요청과 받은 친구 요청 중에서, 친구 상태가 'ACCEPT(수락됨)' 상태인 경우만 필터링하여 친구 목록을 조회합니다.
- 친구 목록 및 친구 삭제 기능에 대한 Swagger 테스트 추가 예정
- 기능 정상 동작
- 코드 스타일 및 컨벤션 준수
- 기존 테스트 통과 
Close #98

[ Feature ] 친구 목록 조회 기능 구현

---

src/main/java/com/samsamhajo/deepground/calendar/controller/MemberStudyScheduleController.java
src/main/java/com/samsamhajo/deepground/calendar/dto/MemberScheduleCalendarResponseDto.java
src/main/java/com/samsamhajo/deepground/calendar/exception/ScheduleErrorCode.java
src/main/java/com/samsamhajo/deepground/calendar/repository/MemberStudyScheduleRepository.java
src/main/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleService.java
src/test/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleServiceTest.java

* 특정 멤버가 자신의 캘린더에 들어갔을 때, 본인의 모든 일정을 확인할 수 있도록 조회 API를 구현했습니다.
- MemberStudyScheduleController에 GET API 추가
- MemberStudyScheduleService에 조회 로직 구현
- MemberScheduleCalendarResponseDto 작성
- 서비스 테스트 코드 작성 및 성공/실패 케이스 검증
* 현재는 PathVariable로 memberId를 받아 일정 목록을 조회하지만
추후에는 로그인 된 사용자 정보를 기반으로 본인의 일정을 조회하도록 리팩토링할 예정입니다.
- 멤버 ID로 정상 조회되는 경우
- 존재하지 않는 멤버 ID로 조회 시 예외 발생 (ScheduleException)
- 연관된 StudySchedule의 정보까지 포함되는지 검증
---
closes #89

[Feature] 특정 멤버의 전체 일정 조회 API 구현

---

src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupMyListResponse.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupServiceMyListTest.java

- 특정 사용자가 생성한 스터디 그룹 목록을 `createdAt` 기준 내림차순으로 조회하는 기능을 구현했습니다.
- 주로 마이페이지 혹은 개인 관리 페이지에서 활용될 수 있는 기능입니다.
---
-  `StudyGroupRepository`에 `findAllByMember_IdOrderByCreatedAtDesc(Long memberId)` 메서드 추가
-  `StudyGroupService`에 `findMyStudyGroups(Long memberId)` 로직 구현
-  응답 DTO `StudyGroupMyListResponse` 정의
-  API 컨트롤러 `/study-group/my/{memberId}` 엔드포인트 추가
-  통합 테스트 `StudyGroupServiceMyListTest` 작성 (정렬 순서, 빈 목록 처리 포함)
-  테스트 환경용 JWT_SECRET 문제 해결 (`@TestPropertySource` 적용 및 base64 + 256bit key 주입)
---
|구조|설명|
|:--|:--|
|`StudyGroupMyListResponse`|`title`, `createdAt`, `groupStatus`를 포함한 요약 응답 DTO|
|`StudyGroupService`|`findMyStudyGroups(memberId)`에서 Repository 호출 후 DTO로 변환|
---
```http
GET /study-group/my/{memberId}
```
- 인증 없이 `memberId` 경로 변수 기반 조회
- 추후 인증된 사용자 본인만 접근할 수 있도록 개선 가능
---
|테스트 …

[Feature] 내가 생성한 스터디 목록 조회 기능 구현

---

src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupParticipationResponse.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupMemberRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupParticipationServiceTest.java

- 로그인한 사용자가 **참여 승인된 스터디 그룹 목록**을 조회할 수 있는 기능을 추가했습니다.
- `StudyGroupMember` 엔티티를 기준으로 필터링하여 응답 DTO에 스터디 정보(제목, 생성자, 참여일)를 요약해 제공합니다.
---
-  `StudyGroupParticipationResponse` DTO 생성
-  `StudyGroupService` 서비스 클래스 및 참여 목록 조회 메서드 구현
-  `StudyGroupMemberRepository`에 쿼리 메서드 추가
-  `StudyGroupController` 컨트롤러 기능 구현
-  통합 테스트 (`StudyGroupParticipationServiceTest`) 작성
- `StudyGroupParticipationResponse`를 통해 필요한 정보만 가공해 반환
- 참여 상태가 `isAllowed = true`인 경우만 필터링하여 반환
| 클래스                               | 설명                  |
| --------------------------------- | ------------------- |
| `StudyGroupService`               | 로그인 사용자의 참여 스터디 조회  |
| `StudyGroupParticipationResponse` | 스터디 제목, 작성자, 참여일 요약 |
---
- `GET /api/v1/{memberId}/joined`
- JWT 기반 인증을 통해 현재 로그인한 사용자 식별
- 서비스 계층 호출을 통해 참여 중인 스터디 목록 반환 …

[Feature] 내가 참여 중인 스터디 그룹 목록 조회 기능 구현

---

src/main/java/com/samsamhajo/deepground/auth/jwt/WebSocketInterceptor.java
src/main/java/com/samsamhajo/deepground/chat/controller/ChatMessageController.java
src/main/java/com/samsamhajo/deepground/chat/dto/ChatMessageRequest.java
src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java
src/main/java/com/samsamhajo/deepground/global/config/WebSocketConfig.java
src/main/java/com/samsamhajo/deepground/global/config/WebSocketSecurityConfig.java
src/main/java/com/samsamhajo/deepground/utils/destination/DestinationUtils.java
src/test/java/com/samsamhajo/deepground/chat/service/ChatMessageServiceTest.java
src/test/java/com/samsamhajo/deepground/utils/destination/DestinationUtilsTest.java

* WebSocket에서 인증된 사용자 정보를 가져올 수 있습니다.
- `WebSocketInterceptor` 구현
- `DestinationUtils` 수정 및 테스트 코드 작성
- 기능 정상 동작 확인
- `JwtAuthenticationFilter`와 `WebSocketInterceptor`에 중복되는 코드가 있습니다.
- 리팩토링할 때 공통 로직을 분리하는 것도 좋을 것 같습니다!
Closes #197

[Feature] WebSocket 연결 시 JWT 기반 인증

---

src/main/java/com/samsamhajo/deepground/feed/feed/controller/FeedController.java
src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedErrorCode.java
src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedSuccessCode.java
src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedMediaService.java
src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedService.java
src/main/java/com/samsamhajo/deepground/media/MediaErrorCode.java
src/main/java/com/samsamhajo/deepground/media/MediaUtils.java
src/test/java/com/samsamhajo/deepground/feed/feed/service/FeedServiceTest.java
src/test/java/com/samsamhajo/deepground/media/MediaUtilsTest.java

피드 글 및 피드 미디어 삭제하기 구현
- `media` directory 내 물리적 삭제 여부 확인 완료
- 피드 생성 -> 피드 삭제 순서로 진행하여 각 단계별 데이터 베이스 반영여부 확인 완료
Feed가 삭제되면, Feed와 연관관계를 맺은 엔티티도 삭제되어야 합니다. 
삭제 로직을 구현하기 전에 관련된 엔티티 서비스 로직 구현을 먼저 진행해야 했을 것 같다고 생각했습니다🥲
추후 서비스 로직 추가 시, 피드 삭제 로직에 연관 엔티티도 같이 삭제되도록 구현하겠습니다.

[Feature] 피드 글 삭제하기

---

src/main/java/com/samsamhajo/deepground/feed/feed/controller/FeedController.java
src/main/java/com/samsamhajo/deepground/feed/feed/controller/FeedLikeController.java
src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedErrorCode.java
src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedSuccessCode.java
src/main/java/com/samsamhajo/deepground/feed/feed/repository/FeedLikeRepository.java
src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedLikeService.java
src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedMediaService.java
src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedService.java
src/main/java/com/samsamhajo/deepground/media/MediaErrorCode.java
src/main/java/com/samsamhajo/deepground/media/MediaUtils.java
src/test/java/com/samsamhajo/deepground/feed/feed/service/FeedLikeServiceTest.java
src/test/java/com/samsamhajo/deepground/feed/feed/service/FeedServiceTest.java
src/test/java/com/samsamhajo/deepground/media/MediaUtilsTest.java

피드 글 좋아요 추가 및 삭제 API 구현하였습니다.
- 데이터베이스 반영 여부 확인
- 데이터베이스 반영 여부 확인
추후 피드 삭제하기 로직이 수행될 경우, 피드 좋아요도 제거되도록 코드 작성하겠습니다.
아쉽거나 부족한 부분이 있다면 리뷰로 말씀 부탁드립니다. 

[Feature] 피드 글 좋아요 추가/삭제 구현

---

src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupReplyController.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupReplyRequest.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupReplyResponse.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupReplyRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupReplyService.java
src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupReplyServiceTest.java

- 기존 댓글에 대한 답글을 작성할 수 있는 기능을 구현했습니다.
이를 통해 댓글 스레드 구조가 가능해졌으며, 추후 스터디 상세 페이지에서 트리 형태의 커뮤니케이션 UI 구현이 가능해집니다.
---
- StudyGroupReplyRequest / StudyGroupReplyResponse DTO 추가
- StudyGroupReplyService 서비스 로직 구현
- StudyGroupReplyRepository 작성
- StudyGroupReplyController 추가 (memberId PathVariable 방식으로 작성자 주입)
- 통합 테스트 StudyGroupReplyServiceTest 작성
|**메서드**|**경로**|
|---|---|
|POST|/study-group/replies/{memberId}|
- 요청 JSON: { commentId: Long, content: String }
- 응답 JSON: replyId, parentCommentId, writerNickname, content, createdAt
---
- 인증 기반으로 @AuthenticationPrincipal 적용 예정 (현재는 memberId PathVariable 사용 중)
---
- 정상적인 답글 작성 흐름 검증
- 존재하지 않는 댓글에 답글 작성 시 예외 검증
- DTO 필드 매핑 및 응답 값 검증
- 영속성 컨텍스트 분리 확인 (flush + clear)
```
assertThat(response.getWriterNickname()).isEqualTo("답글작성자"); …
```

[Feature] 댓글에 대한 답글(대댓글) 작성 기능 추가

---

src/main/java/com/samsamhajo/deepground/auth/controller/AuthController.java
src/main/java/com/samsamhajo/deepground/auth/service/AuthService.java
src/main/java/com/samsamhajo/deepground/auth/success/AuthSuccessCode.java
src/test/java/com/samsamhajo/deepground/auth/service/LogoutTest.java

로그아웃 기능을 구현했습니다.
1. 로그아웃 API 구현 (/api/v1/auth/logout)
- 현재 인증된 사용자의 Refresh Token 삭제
- Redis에서 토큰 정보 제거
- @AuthenticationPrincipal을 통한 현재 사용자 식별
2. Redis 연동
- Refresh Token 저장소에서 토큰 삭제
- memberId를 key로 사용 (RT:{memberId})
3. 테스트 코드 작성
- 로그아웃 기능 단위 테스트
- Redis 연동 테스트

[Feature] 로그아웃 기능 구현

---

src/main/java/com/samsamhajo/deepground/auth/controller/OAuthController.java
src/main/java/com/samsamhajo/deepground/auth/oauth/CustomOAuth2UserService.java
src/main/java/com/samsamhajo/deepground/auth/oauth/OAuth2AuthenticationSuccessHandler.java
src/main/java/com/samsamhajo/deepground/auth/oauth/OAuthAttributes.java
src/main/java/com/samsamhajo/deepground/auth/security/CustomUserDetails.java
src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java
src/main/java/com/samsamhajo/deepground/member/entity/Member.java
src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
src/main/resources/application.yml
src/test/java/com/samsamhajo/deepground/auth/oauth/CustomOAuth2UserServiceTest.java

구글, 카카오, 네이버 등 소셜 로그인(OAuth2) 기능을 구현했습니다.
- OAuth2 소셜 로그인 통합
- 구글/카카오/네이버 OAuth2 연동
- Spring Security 기반 인증 플로우 적용
- 각 provider별 사용자 정보 파싱 및 회원 엔티티 매핑
- 회원 정보 저장 및 동기화
- 최초 로그인 시 신규 회원 자동 등록
- 이미 가입된 경우 닉네임 등 정보 자동 업데이트
- provider별(구글/카카오/네이버) 별도 관리
- JWT 발급 및 인증 처리
- 소셜 로그인 성공 시 JWT(Access/Refresh Token) 발급
- Access Token 만료 시 Refresh Token 통한 재발급 지원
- 콜백/리다이렉트 처리
- Spring Security SuccessHandler에서 프론트엔드로 토큰 전달
- redirect-uri 환경변수 및 소셜 콘솔 등록 일치 관리
- 테스트 코드 작성
- 서비스 단위 테스트: 신규 회원, 정보 업데이트, provider별 파싱 등 검증
- Mock/Mockito 기반 단위 테스트 및 통합 테스트
1. 사용자가 소셜 로그인 버튼 클릭
2. Spring 서버가 provider별 인증 URL로 리다이렉트
3. 소셜 인증 서버에서 로그인/동의 후 콜백 URL로 code 전달
4. 서버가 code로 access token/refresh token 교환
5. 사용자 정보 파싱 후 회원 저장/업데이트
6. JWT 발급 및 프론트엔드로 리다이렉트
- 구글 
- 네이버
- 구글/카카오/네이버 최초 로그인 시 회원 자동 등록되는지 확인
- 이미 가입된 소셜 …

[Feature] 소셜 로그인 기능 구현

---

src/main/java/com/samsamhajo/deepground/calendar/controller/MemberStudyScheduleController.java
src/main/java/com/samsamhajo/deepground/calendar/dto/MemberScheduleDetailResponseDto.java
src/main/java/com/samsamhajo/deepground/calendar/dto/MemberStudyScheduleResponseDto.java
src/main/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleService.java
src/test/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleServiceTest.java

* 단일 일정 상세 조회 API 구현 & 전체 일정 조회 응답 필드 수정
-  단일 일정 상세 조회 API 구현
- 전체 일정 조회 응답 DTO (MemberScheduleCalendarResponseDto)에서 description, location 등 불필요한 필드 제거
- MemberStudyScheduleResponseDto에 정적 팩토리 메서드 from() 추가로 서비스 응답 로직 리팩토링
- 단일 일정 ID로 상세 조회 시 title, startTime 등 정확히 응답되는지 확인
- 존재하지 않는 일정 ID 요청 시 ScheduleException 발생하는지 확인
- 기존 테스트 모두 통과
---
closes #88

[Feature]  단일 일정 상세 조회 API 구현

---

src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyController.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReply.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyLike.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyMedia.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplyErrorCode.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplyException.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplySuccessCode.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FeedReplyCreateRequest.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyMediaRepository.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyRepository.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyMediaService.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyService.java
src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyServiceTest.java

피드 답글 작성하기 API 구현 하였습니다.
- DB 실제 반영 확인
추가적으로 고려해야할 상황이 있다면 말씀 부탁드립니다.
---
closing #78

[Feature] 피드 답글 작성하기

---

src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupDetailResponse.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupMemberRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupAcceptService.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupMemberQueryService.java

📌 개요
- 스터디장(스터디 생성자)이 대기 상태의 신청자를 수락할 수 있는 기능을 추가했습니다.
- 수락 시 해당 신청자는 정식 멤버(isAllowed = true)로 등록됩니다.
🛠️ 작업 내용
- 스터디 신청 수락 API 구현
- StudyGroupAcceptRequest DTO 정의
- StudyGroupAcceptService 생성 및 비즈니스 로직 분리
- 스터디장 권한 검증 로직 추가
- 중복 수락 방지
- 관련 이슈 번호 (#이슈번호)
🔹 주요 로직
- 요청자의 ID와 스터디 생성자의 ID를 비교하여 권한 확인
- 존재하지 않는 스터디 또는 멤버일 경우 예외 발생
- 이미 수락된 멤버는 다시 수락 불가
```
if (!Objects.equals(studyGroup.getCreator().getId(), requester.getId())) {
throw new AccessDeniedException("스터디장만 수락할 수 있습니다.");
}
```
---
📌 기타 참고 사항
- 기존의 StudyGroupMember 엔티티 구조를 활용하여 최소 변경으로 구현
- 도메인 책임은 서비스 계층에서 처리하도록 분리
- 컨트롤러는 단순 위임만 담당
---
🙏🏻 리뷰어 참고사항
- 수락 조건 및 권한 검증 로직이 충분히 명확한지 확인 부탁드립니다.
- 중복 수락 방지 조건이 누락되지 않았는지 검토해주세요.
- 예외 처리 메시지나 응답 코드가 일관성 있게 적용되어 있는지 확인해주세요.
Closes #287

[Feature] 스터디장 스터디 수락 기능 구현

---

src/main/java/com/samsamhajo/deepground/calendar/dto/MemberScheduleCalendarResponseDto.java
src/main/java/com/samsamhajo/deepground/calendar/repository/MemberStudyScheduleRepository.java

- 멤버 스터디 일정 조회 시 StudyGroup ID도 같이 조회되도록 수정
- MemberScheduleCalendarResponseDto에 studyGroupId 필드 추가
- MemberStudyScheduleRepository에 fetch join 쿼리 적용
- from() 팩토리 메서드에서 studyGroupId 추출 로직 추가
- N+1 문제 콘솔 확인 완료
- 프론트 연동 수정 예정
- 기능 정상 동작 확인
---
closes #291

[Feature] 멤버스터디dto에 studyGroupId 필드 추가

---

src/main/java/com/samsamhajo/deepground/calendar/service/StudyScheduleService.java
src/test/java/com/samsamhajo/deepground/calendar/service/StudyScheduleServiceTest.java

스터디 그룹 리더를 반환하는 메서드명을 getMember() → getCreator()로 변경하여 의미 명확화
- StudyGroup 도메인의 getMember() 메서드명 변경
---
closes #293

[Refactor] StudyGroup의 getMember()를 getCreator()로 변경

---

build.gradle
src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedMediaService.java
src/main/java/com/samsamhajo/deepground/global/config/S3Config.java
src/main/java/com/samsamhajo/deepground/global/upload/S3Uploader.java
src/main/java/com/samsamhajo/deepground/global/upload/exception/UploadErrorCode.java
src/main/java/com/samsamhajo/deepground/global/upload/exception/UploadException.java
src/main/java/com/samsamhajo/deepground/member/Dto/MemberProfileDto.java
src/main/java/com/samsamhajo/deepground/member/controller/MemberController.java
src/main/java/com/samsamhajo/deepground/member/service/MemberService.java
src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerMediaService.java
src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionMediaService.java
src/main/resources/application.yml
src/test/java/com/samsamhajo/deepground/member/service/ProfileTest.java

- AWS S3 연동을 위한 설정 및 파일 업로드 유틸 클래스(S3Uploader)를 추가했습니다
- s3 관련 `builde.grade` 추가
- S3 관련 프로퍼티 및 yml 파일 설정
- S3Uploader 유틸 클래스 구현
- 예외 처리용 `UploadException`, `UploadErrorCode` 정의
- 피드 , 질문 , 댓글 관련 미디어 서비스 로직 리팩토링 (`FeedMediaService`,`AnswerMediaService`,`CommentMediaService`
- 프로필 편집 관련 로직 사진 업로드 로직 추가 (`editMemberProfile`,
- 기능 정상 동작 
- 새로운 의존성 추가 (`build.gradle`,`application.yml`)
- 코드 스타일 및 컨벤션 준수
- 기존 테스트 통과
- 파일이 실제 AWS S3에 저장되는지 확인
- 업로드 경로는 `dirName/UUID+파일명` 구조로 저장됨
- 현재는 공개 접근 권한으로 업로드됨 (추후 권한 설정 기능 고려 필요)
---
Close #303

[Feature] 파일 서버 AWS s3 연동 로직 구현 

---

src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupDetailResponse.java
src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupMemberStatus.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupCommentRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupMemberRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupReplyRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupServiceDetailsTest.java

* 스터디 상세 조회 시 현재 로그인한 사용자의 참여 상태(`미신청`, `신청 완료`, `참여 중`)를 명확히 판단하고 클라이언트에 전달할 수 있도록 설계 개선.
* 기존에는 단순히 `isAllowed`로만 참여 여부를 구분했으나, 신청 여부 자체를 구분하지 못하는 문제가 있었음
* 이를 해결하기 위해 `StudyGroupMemberStatus` enum을 도입하여 다음 3단계로 상태를 분리:
- 미신청: 해당 스터디에 아무 기록 없음
- 신청 완료: 신청했으나 승인되지 않음
- 참여 중: 신청 및 승인 완료
* 서비스 계층에서 `Optional<StudyGroupMember>`를 조회한 뒤 상태를 판단하여 `StudyGroupDetailResponse`로 전달
* 스터디 상세 페이지에서 버튼 UI 상태 (예: 신청하기/신청 완료/참여 중 등)를 `memberStatus` 값 기반으로 렌더링할 수 있도록 프론트엔드 연동 예정
* 관리자가 참여자 승인 시 상태 변경 관련 이벤트 트리거 기능 추가 가능성 검토
* 테스트한 내용:
- `StudyGroupMember`가 존재하지 않는 경우 `NOT_APPLIED`로 응답되는지 확인
- 존재하지만 `isAllowed = false`일 경우 `PENDING`으로 응답되는지 확인
- `isAllowed = true`일 경우 `APPROVED`로 응답되는지 확인
- 단순한 Boolean 대신 Enum으로 분리하여 유지보수성과 확장성 증가
- 추후 상태 변경 시점(예: 승인, 거절, 취소 등) 관리도 용이해짐
---
- 코드 …

[Feature] 스터디 참여 상태 분기 로직 및 응답 필드 추가
