src/main/java/com/samsamhajo/deepground/interest/entity/Interest.java
src/main/java/com/samsamhajo/deepground/interest/entity/MemberInterest.java
src/main/java/com/samsamhajo/deepground/member/entity/Member.java
src/main/java/com/samsamhajo/deepground/member/entity/Provider.java
src/main/java/com/samsamhajo/deepground/techStack/entity/MemberTechStack.java
src/main/java/com/samsamhajo/deepground/techStack/entity/TechStack.java

`[Feature] Member , Interest, TechStack 엔티티 구현`
- Member, Interest, TechStack 도메인의 기본 엔티티를 구현하였습니다.
- Member 엔티티에서 일반 회원가입과 소셜 로그인을 모두 지원하도록 설계하였습니다.
- Interest와 Member 간의 다대다 관계를 매핑하였습니다.
- TechStack과 Member 간의 다대다 관계를 매핑하였습니다.
* 기본 정보 필드 구현
- 이메일, 비밀번호, 닉네임 등 사용자 기본 정보
- 프로필 이미지, 자기소개 등 부가 정보
- 회원가입 방식(Provider) 및 인증 여부 정보
* 제약조건 설정
- ID: NOT NULL (PK)
- email: NOT NULL (사용자 식별용)
- nickname: NOT NULL (서비스 내 표시명)
- is_verified: NOT NULL (인증 여부)
- provider: NOT NULL (가입 방식)
- password: NULL 가능 (소셜 로그인 시 불필요)
- profile_image: NULL 가능 (선택사항)
- introduction: NULL 가능 (선택사항)
- provider_id: NULL 가능 (일반 회원가입 시 불필요)
1. Interest 엔티티
* 기본 정보 필드 구현
- 관심사의 이름과 카테고리 정보 정의
* 제약조건 설정
- interest_id: NOT NULL (PK)
- interest_name: NOT NULL (관심사 이름)
- interest_category: NULL 가능 (카테고리 분류)
2. MemberInterest …

[Feature] 멤버, 관심사, 기술 스택 엔티티 구현

---

src/main/java/com/samsamhajo/deepground/calendar/entity/StudySchedule.java

* 스터디 스케줄(StudySchedule) 엔티티를 생성하여 스터디 그룹의 일정 관리를 위한 기본 데이터 구조를 설계했습니다.
* 스터디 그룹 내 일정을 관리하기 위한 StudySchedule 엔티티를 새로 생성했습니다.
* 주요 필드는 다음과 같습니다:
- `title`: 스케줄 제목
- `startTime`, `endTime`: 일정 시작 및 종료 시간
- `description`: 스케줄 설명 (optional)
- `location`: 스케줄 장소 (optional)
* `StudyGroup` 엔티티와의 다대일(`@ManyToOne`) 연관관계를 맺기 위한 필드를 주석으로 추가해두었습니다.
* 추후 `StudyGroup` 엔티티 개발 및 연동 작업이 완료된 이후, 주석을 해제하고 연관관계 매핑을 완료할 예정입니다.
- close #22
* MemberStudySchedule 엔티티 구현 예정
* 현재는 StudyGroup 연관관계를 주석 처리하여 반영하지 않았으며, 추후 StudyGroup 개발 이후 연관관계 매핑을 추가할 예정입니다.
---

[Feature] 스터디 스케줄 엔티티 구현

---

src/main/java/com/samsamhajo/deepground/chat/entity/ChatRoom.java
src/main/java/com/samsamhajo/deepground/chat/entity/ChatRoomType.java

* 채팅방 정보를 저장하는 `ChatRoom` 엔티티를 생성하였습니다.
- `ChatRoom` 엔티티 클래스 생성
- `ChatRoomType` enum 클래스 생성
- 관련 이슈 번호 #36 
- `chat_room_id`: 채팅방 고유 ID
- `chat_room_type`: 채팅방 타입
- `FRIEND`: 친구 채팅
- `STUDY_GROUP`: 스터디 그룹 채팅
- 채팅방 멤버 엔티티 클래스 구현
- `ChatRoom` 테이블 생성 확인
- 새로운 의존성 없음
---
Closes #36

[Feature] ChatRoom 엔티티 구현

---

src/main/java/com/samsamhajo/deepground/feed/feed/entity/Feed.java
src/main/java/com/samsamhajo/deepground/feed/feed/entity/FeedLike.java
src/main/java/com/samsamhajo/deepground/feed/feedcomment/entity/FeedComment.java
src/main/java/com/samsamhajo/deepground/feed/feedcomment/entity/FeedCommentLike.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReply.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyLike.java
src/main/java/com/samsamhajo/deepground/feed/feedshared/entity/SharedFeed.java

- 일부 피드 관련 엔티티와 Member에 대해 연관관계 매핑 수행
- 정적 팩토리 메서드 패턴을 적용
- Repository, Service, Controller Layer 구현
- 서비스 로직 작성
정상 빌드 여부 및 데이터베이스 적용 확인 하였습니다.
우려되는 점이나 궁금한 점이 있으실 경우 말씀 부탁드립니다.
---

[Refactor] 피드 관련 엔티티 연관관계 매핑

---

src/main/java/com/samsamhajo/deepground/qna/answer/entity/Answer.java
src/main/java/com/samsamhajo/deepground/qna/answer/entity/AnswerLike.java
src/main/java/com/samsamhajo/deepground/qna/answer/entity/AnswerMedia.java
src/main/java/com/samsamhajo/deepground/qna/comment/entity/Comment.java
src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
src/main/java/com/samsamhajo/deepground/qna/question/entity/QuestionMedia.java
src/main/java/com/samsamhajo/deepground/qna/question/entity/QuestionTag.java

- 질문, 댓글, 답변 연관관계 매핑
- 연관관계 생성자 작성
의견이나 잘못된 점 있으시면 편하게 남겨주세요!
---

[Refactor] 질문, 댓글, 답변 연관관계 생성자 & 매핑

---

src/main/java/com/samsamhajo/deepground/notification/entity/Notification.java
src/main/java/com/samsamhajo/deepground/notification/entity/NotificationMessage.java
src/main/java/com/samsamhajo/deepground/notification/entity/data/ChatMessageNotificationData.java
src/main/java/com/samsamhajo/deepground/notification/entity/data/FriendRequestNotificationData.java
src/main/java/com/samsamhajo/deepground/notification/entity/data/NotificationData.java
src/main/java/com/samsamhajo/deepground/notification/entity/data/StudyGroupNotificationData.java
src/main/java/com/samsamhajo/deepground/notification/entity/data/StudyScheduleNotificationData.java

* 알림 관련 엔티티에 정적 팩토리 메서드를 추가했습니다.
- 알림 관련 엔티티에 정적 팩토리 메서드 추가
- 변수명 변경 `Notification` 엔티티의 `notificationMessage` -> `message`
* 알림 기능 구현
- 기능 정상 동작 확인
---
Closes #56

[Refactor] 알림 관련 엔티티에 정적 팩토리 메서드 추가

---

src/main/java/com/samsamhajo/deepground/global/error/core/BaseException.java
src/main/java/com/samsamhajo/deepground/global/error/core/ErrorCode.java
src/main/java/com/samsamhajo/deepground/global/error/core/ErrorResponse.java
src/main/java/com/samsamhajo/deepground/global/error/handler/GlobalErrorCode.java
src/main/java/com/samsamhajo/deepground/global/error/handler/GlobalExceptionHandler.java
src/main/java/com/samsamhajo/deepground/global/success/SuccessCode.java
src/main/java/com/samsamhajo/deepground/global/success/SuccessResponse.java
src/main/java/com/samsamhajo/deepground/global/utils/GlobalLogger.java

응답 표준 정의 및 글로벌 기능 구현
정의된 표준 코드를 이용하여, 응답 및 예외처리를 수행하도록 합니다.
타 프로젝트에서 동작 검증은 확인했으나, 본 프로젝트에서는 시도하지는 않았습니다.
다만, 별도의 의존성이 필요하지 않으며 기능 자체는 간단한 코드라서 규칙만 지키시면 동작 오류가 나진 않을겁니다.
관련해서 궁금한 부분이 있다면 코멘트 혹은 디스코드로 말씀 부탁 드립니다.
close #62 #63

[Feature] 응답 표준 정의 및 글로벌 기능 구현

---

build.gradle
src/main/java/com/samsamhajo/deepground/global/config/WebSocketSecurityConfig.java

* WebSocketSecurity와 스웨거 충돌로 인한 주석 처리
- WebSocketSecurityConfig 주석 처리
- 기능 정상 동작 확인
---
Closes #66

[Fix] 스웨거 충돌로 인한 주석 처리

---

src/main/java/com/samsamhajo/deepground/global/config/JpaConfig.java

* `Column 'created_at' cannot be null` 오류가 발생하여 Jpa 설정을 추가했습니다.
- `@EnableJpaAuditing` 설정 추가
- 기능 정상 동작 확인
---

[Fix] @EnableJpaAuditing 설정 추가

---

src/main/java/com/samsamhajo/deepground/chat/entity/ChatRoom.java
src/main/java/com/samsamhajo/deepground/chat/redis/ChatRedisKeys.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatMessageRepository.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatRoomMemberRepository.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatRoomRepository.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatRedisService.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatRoomMemberService.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatRoomService.java
src/main/java/com/samsamhajo/deepground/external/redis/RedisKey.java
src/main/java/com/samsamhajo/deepground/external/redis/RedisManager.java
src/main/java/com/samsamhajo/deepground/utils/redis/RedisUtil.java
src/test/java/com/samsamhajo/deepground/chat/service/ChatRoomMemberServiceTest.java
src/test/java/com/samsamhajo/deepground/chat/service/ChatRoomServiceTest.java

* 채팅방 참여 기능을 구현했습니다.
* 스터디 그룹에 새로운 멤버가 추가될 때 호출되어야 합니다. (`joinChatRoom`)
- Redis에 값을 저장하고 가져오는 `RedisManager` 구현
- 채팅방의 최근 메시지 시간을 조회하는 메서드 구현 (`getLatestMessageTime`)
- 채팅방에 초기 멤버를 추가하는 메서드 구현 (`addInitialMember`)
- 채팅방 참여 기능 구현 (`joinChatRoom`)
- `ChatRoomMemberServiceTest` 단위 테스트 작성
* Redis에 데이터가 있는지 확인하고, 없으면 DB에서 조회한 후 Redis에 저장하는 `Cache Aside` 패턴을 적용했습니다.
* 의도하지 않은 문자열이 Key로 사용되는 것을 방지하기 위해 `RedisKey`를 추가했습니다.
- 기능 정상 동작 확인 (단위 테스트)
- 기존 테스트 통과
Closes #101

[Feature] 채팅방 참여 기능 구현

---

src/main/java/com/samsamhajo/deepground/chat/entity/ChatRoom.java
src/main/java/com/samsamhajo/deepground/chat/entity/ChatRoomMember.java
src/main/java/com/samsamhajo/deepground/chat/exception/ChatRoomErrorCode.java
src/main/java/com/samsamhajo/deepground/chat/exception/ChatRoomException.java
src/main/java/com/samsamhajo/deepground/chat/redis/ChatRedisKeys.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatMessageRepository.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatRoomMemberRepository.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatRoomRepository.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatRedisService.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatRoomMemberService.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatRoomService.java
src/main/java/com/samsamhajo/deepground/external/redis/RedisKey.java
src/main/java/com/samsamhajo/deepground/external/redis/RedisManager.java
src/main/java/com/samsamhajo/deepground/utils/redis/RedisUtil.java
src/test/java/com/samsamhajo/deepground/chat/service/ChatRoomMemberServiceTest.java
src/test/java/com/samsamhajo/deepground/chat/service/ChatRoomServiceTest.java

* 채팅방 삭제 기능을 구현했습니다.
* 친구가 삭제되었을 때, 스터디 그룹이 삭제되었을 때 호출되어야 합니다. (`deleteChatRoom`)
- 채팅방 삭제 기능 구현 (`deleteChatRoom`)
- 단위 테스트 작성
* `ChatRoom`을 찾을 수 없다면, 에러(`ROOM_NOT_FOUND`)가 발생합니다.
* JPQL을 사용해 채팅방에 속한 모든 멤버를 soft delete 합니다. (`softDeleteByChatRoomId`)
* `ChatRoom`의 `softDelete`를 호출합니다.
- 기능 정상 동작 확인
- 기존 테스트 통과
Closes #103

[Feature] 채팅방 삭제 기능 구현

---

src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionRequestDto.java
src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
src/main/java/com/samsamhajo/deepground/qna/question/entity/QuestionStatus.java
src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionErrorCode.java
src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionException.java
src/main/java/com/samsamhajo/deepground/qna/question/repository/QuestionRepository.java
src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java
src/main/resources/application.yml
src/test/java/com/samsamhajo/deepground/IntegrationTestSupport.java
src/test/java/com/samsamhajo/deepground/question/QuestionTest.java

* 질문 글 작성 구현
member관련해서는 일단 주석처리 해놓아서 추후에 작업할 예정입니다.
프로젝트가 처음이라 이것저것 많이 찾아보면서 코드 작성한 느낌이라 자유롭게 의견주시면 반영하도록 하겠습니다!
---

[Feature] Question 작성 구현

---

build.gradle
src/main/java/com/samsamhajo/deepground/feed/feed/controller/FeedController.java
src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedErrorCode.java
src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedException.java
src/main/java/com/samsamhajo/deepground/feed/feed/model/FeedCreateRequest.java
src/main/java/com/samsamhajo/deepground/feed/feed/repository/FeedRepository.java
src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedService.java
src/test/java/com/samsamhajo/deepground/feed/feed/controller/FeedControllerTest.java
src/test/java/com/samsamhajo/deepground/feed/feed/service/FeedServiceTest.java

피드 글 작성하기 구현
- content null 여부 유효성 검증을 Controller Layer에서 수행할 수 있도록 변경
- 생성 및 실패 테스트에 대한 기능 정상 동작 확인
- 기존 테스트 통과
@RequestParam Long memberId 등 적절하지 못한 부분들이 있습니다. 이는 이후 PR에서 수정되었으니 양해 부탁드립니다.
이미 언급되어 있다 해도, 이상한 부분들이 있다면 리뷰 남겨주세요.
---
closing #68

[Feature] 피드 글 작성하기 구현

---

src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java

- Spring Security 설정(SecurityConfig) 개선
- 인증이 필요 없는 엔드포인트(/auth/**, Swagger 관련 경로 등)에 대한 접근 허용 및 CSRF 보호 비활성화
- Postman 등 외부 클라이언트에서의 API 테스트 편의성 향상

[Refactor] Security 관련 Config 수정

---

src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionSuccessCode.java
src/test/java/com/samsamhajo/deepground/question/QuestionTest.java

[Refactor] Q&A 응답표준 코드 리팩토링

---

src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionResponseDto.java
src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionUpdateDto.java
src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionErrorCode.java
src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionSuccessCode.java
src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java
src/test/java/com/samsamhajo/deepground/question/QuestionTest.java
src/test/java/com/samsamhajo/deepground/question/QuestionUpdateTest.java

질문 수정 로직 구현
추후에 Media, TechStack 로직 질문 삭제 로직 구현 후에 한번에 추가할 예정입니다.
잘 모르는 부분이 많아, 다양한 의견, 고칠 점 있으면 자유롭게 말씀해주시면 감사하겠습니다!!
---

[Feature] 질문 수정 기능 구현

---

src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionSuccessCode.java
src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java
src/test/java/com/samsamhajo/deepground/question/AnswerTest.java
src/test/java/com/samsamhajo/deepground/question/QuestionDeleteTest.java
src/test/java/com/samsamhajo/deepground/question/QuestionTest.java

Merge하면서 코드 줄이 겹치거나 한 부분이 있어서 간단히 리팩토링 했습니당
---

[Refactor] Q&A 에러부분 코드 리팩토링

---

src/main/java/com/samsamhajo/deepground/calendar/controller/MemberStudyScheduleController.java
src/main/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleService.java
src/test/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleServiceTest.java

* MemberStudyScheduleService 리팩토링 및 머지 충돌 해결
---
closes #218

[Refactor] MemberStudyScheduleService 리팩토링 및 머지 충돌 해결

---

src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/FeedCommentController.java
src/main/java/com/samsamhajo/deepground/feed/feedcomment/exception/FeedCommentSuccessCode.java
src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentLikeRepository.java
src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentRepository.java
src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeService.java
src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentMediaService.java
src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentService.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyController.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyLikeController.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplySuccessCode.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyLikeRepository.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyRepository.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeService.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyMediaService.java
src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyService.java
src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentServiceTest.java
src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeServiceTest.java
src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyServiceTest.java

피드 답글 좋아요 추가/삭제하기 API 구현하였습니다.
- DB 반영 확인
- DB 반영 확인
좋아요 취소의 경우 softDelete를 하지 않았습니다. 추가적으로 고려해야할 부분이 있다면 말씀 부탁드립니다.
---
closing #232

[Feature] 피드 답글 좋아요 추가/취소하기

---

src/main/java/com/samsamhajo/deepground/chat/entity/ChatMedia.java
src/main/java/com/samsamhajo/deepground/chat/exception/ChatMessageErrorCode.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatMediaRepository.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatMessageService.java
src/test/java/com/samsamhajo/deepground/chat/service/ChatMessageServiceTest.java

- 채팅 미디어 전송 기능을 구현했습니다.
- 채팅 미디어 전송 기능 구현(`ChatMessageService.sendMessage`, `ChatMessageService.messageTextAndMedia`)
- 미디어 Id를 포함하여 메시지를 전송
- 기능 정상 동작 확인
Closes #239

[Feature] 채팅 미디어 전송 기능 구현

---

src/main/java/com/samsamhajo/deepground/DeepgroundApplication.java
src/main/java/com/samsamhajo/deepground/notification/controller/NotificationController.java
src/main/java/com/samsamhajo/deepground/notification/service/NotificationService.java
src/main/java/com/samsamhajo/deepground/sse/controller/SseEmitterController.java
src/main/java/com/samsamhajo/deepground/sse/dto/SseEvent.java
src/main/java/com/samsamhajo/deepground/sse/dto/SseEventType.java
src/main/java/com/samsamhajo/deepground/sse/repository/SseEmitterRepository.java
src/main/java/com/samsamhajo/deepground/sse/repository/SseEmitterRepositoryImpl.java
src/main/java/com/samsamhajo/deepground/sse/service/SseEmitterService.java
src/test/java/com/samsamhajo/deepground/notification/service/NotificationServiceTest.java
src/test/java/com/samsamhajo/deepground/sse/service/SseEmitterServiceTest.java

* (작업한 코드에 대한 간략한 설명해주세요)
- 기능 정상 동작 확인
Closes #252

[Feature] 알림 전송 기능을 WebSocket에서 SSE로 변경

---

src/main/java/com/samsamhajo/deepground/chat/controller/ChatMessageController.java
src/main/java/com/samsamhajo/deepground/chat/dto/ReadMessageRequest.java
src/main/java/com/samsamhajo/deepground/chat/dto/ReadMessageResponse.java
src/main/java/com/samsamhajo/deepground/chat/dto/UnreadCountResponse.java
src/main/java/com/samsamhajo/deepground/chat/entity/ChatRoomMember.java
src/main/java/com/samsamhajo/deepground/chat/exception/ChatMessageErrorCode.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatMessageRepository.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatRoomMemberRepository.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatMessageService.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatRoomMemberService.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatRoomService.java
src/main/java/com/samsamhajo/deepground/sse/dto/SseEventType.java
src/test/java/com/samsamhajo/deepground/chat/service/ChatMessageServiceTest.java

* (작업한 코드에 대한 간략한 설명해주세요)
- 기능 정상 동작 확인
Closes #135

[Feature] 채팅 메시지 읽음 기능 구현

---

src/main/java/com/samsamhajo/deepground/chat/controller/ChatMediaController.java
src/main/java/com/samsamhajo/deepground/chat/controller/ChatMessageController.java
src/main/java/com/samsamhajo/deepground/chat/controller/ChatRoomController.java
src/main/java/com/samsamhajo/deepground/chat/dto/ChatMessageListRequest.java
src/main/java/com/samsamhajo/deepground/chat/dto/ChatMessageListResponse.java
src/main/java/com/samsamhajo/deepground/chat/dto/ChatRoomMemberInfo.java
src/main/java/com/samsamhajo/deepground/chat/dto/ChatRoomResponse.java
src/main/java/com/samsamhajo/deepground/chat/exception/ChatErrorCode.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatMessageCustomRepository.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatMessageCustomRepositoryImpl.java
src/main/java/com/samsamhajo/deepground/chat/repository/ChatMessageRepository.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatMessageService.java
src/main/java/com/samsamhajo/deepground/chat/service/ChatRoomMemberService.java
src/main/java/com/samsamhajo/deepground/chat/success/ChatSuccessCode.java
src/test/java/com/samsamhajo/deepground/chat/service/ChatMessageServiceTest.java
src/test/java/com/samsamhajo/deepground/chat/service/ChatRoomMemberServiceTest.java

* (작업한 코드에 대한 간략한 설명해주세요)
* (작업한 코드에 대한 자세한 설명해주세요. 필요하다면 이미지나 표를 첨부해주세요)
| 이미지① |
| :----: |
| |
* (작업한 코드에 대한 자세한 설명해주세요. 필요하다면 이미지나 표를 첨부해주세요)
| 이미지① |
| :----: |
| |
| 이미지① |
| :----: |
| |
---

[Feature] 채팅 메시지 조회 기능 구현

---

src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java

CORS 설정 추가
* (작업한 코드에 대한 자세한 설명해주세요. 필요하다면 이미지나 표를 첨부해주세요)
| 이미지① |
| :----: |
| |
* (작업한 코드에 대한 자세한 설명해주세요. 필요하다면 이미지나 표를 첨부해주세요)
| 이미지① |
| :----: |
| |
| 이미지① |
| :----: |
| |
---

[Feature] Security Config에 CORS 설정 추가

---

src/main/java/com/samsamhajo/deepground/qna/answer/controller/AnswerController.java
src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerCreateRequestDto.java
src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerCreateResponseDto.java
src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerDetailDto.java
src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerUpdateRequestDto.java
src/main/java/com/samsamhajo/deepground/qna/answer/entity/Answer.java
src/main/java/com/samsamhajo/deepground/qna/answer/entity/AnswerMedia.java
src/main/java/com/samsamhajo/deepground/qna/answer/repository/AnswerMediaRepository.java
src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerMediaService.java
src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerService.java
src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
src/main/java/com/samsamhajo/deepground/qna/question/repository/QuestionMediaRepository.java
src/main/java/com/samsamhajo/deepground/qna/question/repository/QuestionRepository.java
src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionMediaService.java
src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java

답변 이미지 로직 서비스, DTO변경
질문 관련 프로필부분에서 자신이 작성한 질문 부분 로직 작성
| 이미지① |
| :----: |
| |
---

[Refacotr] 답변 이미지, 질문 관련 로직 수정

---

src/main/java/com/samsamhajo/deepground/member/Dto/MemberProfileDto.java
src/main/java/com/samsamhajo/deepground/member/controller/MemberController.java
src/main/java/com/samsamhajo/deepground/member/exception/ProfileErrorCode.java
src/main/java/com/samsamhajo/deepground/member/exception/ProfileSuccessCode.java
src/main/java/com/samsamhajo/deepground/member/service/MemberService.java
src/main/java/com/samsamhajo/deepground/techStack/exception/TechStackErrorCode.java
src/main/java/com/samsamhajo/deepground/techStack/exception/TechStackException.java
src/test/java/com/samsamhajo/deepground/member/service/ProfileTest.java

프로필 생성 및 자신의 프로필 조회 기능을 구현했습니다.
* (작업한 코드에 대한 자세한 설명해주세요. 필요하다면 이미지나 표를 첨부해주세요)
| 이미지① |
| :----: |
| |
* (작업한 코드에 대한 자세한 설명해주세요. 필요하다면 이미지나 표를 첨부해주세요)
| 이미지① |
| :----: |
| |
| 이미지① |
| :----: |
| |
---

[Feature] 프로필 생성 및 자신의 프로필 조회 기능 구현

---

src/main/java/com/samsamhajo/deepground/feed/feed/controller/FeedController.java
src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedSuccessCode.java
src/main/java/com/samsamhajo/deepground/feed/feed/model/FetchFeedSummariesResponse.java
src/main/java/com/samsamhajo/deepground/feed/feed/model/FetchFeedSummaryResponse.java
src/main/java/com/samsamhajo/deepground/feed/feed/repository/FeedRepository.java
src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedMediaService.java
src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedService.java

피드 조회하기, 멤버의 피드 요약 목록 조회하기 구현
---
cloese #316

[Feature] 피드 조회하기, 멤버의 피드 요약 목록 조회하기 구현

---

src/main/java/com/samsamhajo/deepground/global/config/MongoConfig.java

* MongoDB 트랜잭션 적용을 위한 주석 해제 작업입니다.
- `transactionManager` 주석 해제
- **해당 PR을 merge 했을 때, MongoDB가 `Replica Set`이 아니라면 오류가 발생할 수 있습니다.**
- 기능 정상 동작 확인
---
Closes #327

[Fix] MongoDB 트랜잭션 적용

---

src/test/java/com/samsamhajo/deepground/calendar/service/StudyScheduleServiceTest.java

* 테스트 코드에서 mock 객체 추가
* 테스트 코드에서 mock 객체 추가
---

[Feature] 스터디 스케줄 테스트 수정

---

src/main/java/com/samsamhajo/deepground/qna/answer/controller/AnswerController.java
src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerEditResponseDto.java
src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerUpdateResponseDto.java
src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerMediaService.java
src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerService.java
src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionUpdateResponseDto.java
src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionMediaController.java
src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java

[refactor] 기능 검증하면서 추가 로직 수정

---

src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupSearchRequest.java
src/main/java/com/samsamhajo/deepground/studyGroup/entity/OnOffline.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java

스터디 그룹 페이지네이션 조회시 온라인, 오프라인 필터링이 가능하게 추가하였습니다.
현재 제 도메인에서 테스트가 터지는 것으로 확인되었는데, 수정하겠습니다.!
---
Closes #350

[Refactor] 온라인, 오프라인 필터링 추가

---

src/main/java/com/samsamhajo/deepground/auth/dto/LoginResponse.java
src/main/java/com/samsamhajo/deepground/auth/service/AuthService.java
src/main/java/com/samsamhajo/deepground/email/service/EmailService.java
src/main/java/com/samsamhajo/deepground/friend/Dto/FriendDto.java
src/main/java/com/samsamhajo/deepground/member/Dto/MemberProfileDto.java
src/main/java/com/samsamhajo/deepground/member/controller/MemberController.java
src/main/java/com/samsamhajo/deepground/member/entity/Member.java
src/main/java/com/samsamhajo/deepground/member/entity/MemberProfile.java
src/main/java/com/samsamhajo/deepground/member/entity/Role.java
src/main/java/com/samsamhajo/deepground/member/service/MemberService.java
src/main/java/com/samsamhajo/deepground/member/utils/MemberUtils.java
src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/ParticipantSummaryDto.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupMemberSummary.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupMemberService.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java

- 이메일 인증 관련 코드 수정
- 프로필 조회 관련 코드 수정
#352 
closes #352 
---

[Feature] 이메일 인증, 프로필 조회 관련 코드 수정

---

.github/reviewers.yml
.github/workflows/deploy.yml
src/test/java/com/samsamhajo/deepground/member/service/ProfileTest.java

- 프로필_편집_성공 테스트 메서드에서 지역변수 누락으로 인한 오류 발생을 해 누락된 지역변수를 추가했다
- 실행전 초기화 메서드에 `spring` 지역변수 추가
- ci/cd 구축 예정
close #356

[Fix] 프로필 테스트 코드 오류 해결

---

src/main/java/com/samsamhajo/deepground/qna/answer/controller/AnswerController.java
src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionSummaryDto.java

이미지 올라가지 않는 오류 & 상태 표시 해결

---

src/main/java/com/samsamhajo/deepground/calendar/exception/ScheduleErrorCode.java
src/main/java/com/samsamhajo/deepground/calendar/service/StudyScheduleService.java
src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupMemberController.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCommentRequest.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCreateRequest.java
src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupReplyRequest.java
src/main/java/com/samsamhajo/deepground/studyGroup/exception/StudyGroupErrorCode.java
src/main/java/com/samsamhajo/deepground/studyGroup/exception/StudyGroupException.java
src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupCommentService.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupInviteService.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupMemberService.java
src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java

- 스터디 그룹 도메인의 안정성과 신뢰도를 높이기 위해 기존 코드에 누락되었던 예외처리를 추가하고, 일부 로직을 개선했습니다. 이를 통해 잠재적인 동시성 문제를 해결하고, 유효하지 않은 데이터 입력을 방지하며, 사용자에게 더 명확한 피드백을 제공하여 전반적인 서비스 품질을 향상시키는 것을 목표로 합니다.
- **문제점**: 여러 사용자의 스터디 그룹 가입 승인 요청이 동시에 처리될 경우, 최대 멤버 수를 초과하여 가입되는 Race Condition(경쟁 상태)이 발생할 수 있었습니다.
- **해결 방안**: `StudyGroupMemberService`의 `acceptJoinRequest` 메소드에서 스터디 그룹 정보를 조회할 때 **Pessimistic Lock**을 적용하여 데이터 일관성을 보장했습니다. 이를 통해 특정 트랜잭션이 데이터를 처리하는 동안 다른 트랜잭션의 접근을 막아 동시성 문제를 해결했습니다.
```
// StudyGroupRepository.java
@Lock(LockModeType.PESSIMISTIC_WRITE)
Optional<StudyGroup> findById(Long id);
```
- **문제점**: 기존 코드에서는 스터디 그룹장이 그룹 탈퇴를 시도해도 별다른 피드백 없이 요청이 무시되었습니다.
- **해결 방안**: `StudyGroupMemberService`의 `leaveStudyGroup` 메소드에 그룹장일 경우 `MEMBER_IS_LEADER` 에러를 발생시키는 로직을 추가하여, 왜 탈퇴가 불가능한지 명확하게 알 수 있도록 개선했습니다.
- **문제점**: …

[Refactor] 스터디 그룹 도메인 예외 처리 강화 및 로직 개선

---

.github/workflows/deploy.yml
alertmanager/alertmanager.yml
docker-compose.yml
loki/loki-config.yaml
prometheus/alert.rules.yml
prometheus/prometheus.yml
promtail/promtail-config.yaml

Loki, Promtail, AlertManager 설정파일 추가

Loki, Promtail, AlertManager 설정파일 추가
